### ISSUE TITLE
Use the ffmpeg content snap and some more changes

### ISSUE THREAD

**Issue by soumyaDghosh** [ScarlettGatelyMoore/qt-5-15-10-snap#1]
Hi, as I saw you're building ffmpeg from source, you can skip it. And those who need it can use the ffmpeg content snap. Even gnome-sdk also doesn't include ffmpeg. Also, there are some issues with the manifest iteself, like:

https://github.com/ScarlettGatelyMoore/qt-5-15-10-snap/blob/main/snapcraft.yaml#L497

if you explain what you want to search here, I can help you with it.

https://github.com/ScarlettGatelyMoore/qt-5-15-10-snap/blob/main/snapcraft.yaml#L79
here you used old style variables

https://github.com/ScarlettGatelyMoore/qt-5-15-10-snap/blob/main/snapcraft.yaml#L724
here `craftctl stage` doesn't exist. It's `craftctl default` for all. 

Kindly explain me how you want the architecture of these and I can help you fix the mismatches.

**Comment by ScarlettGatelyMoore** [comment]
Merged your removal of ffmpeg. I am reusing code https://github.com/Nightmayr-snaps/nightmayr-qt-sdk and there probably wasn't an ffmpeg snap at the time. I no longer need to search as I am using kde patch set branch and just need to remove all that. I started on a Friday afternoon and didn't get as far as I would have like. I can fix the rest today. Thanks for your contribution!
